add cleanup old images command in cds of all 3 services

diff --git a/.github/workflows/cd_frontend.yml b/.github/workflows/cd_frontend.yml
--- a/.github/workflows/cd_frontend.yml
+++ b/.github/workflows/cd_frontend.yml
@@ -2,7 +2,7 @@ name: Continuous Deployment (Prod) (Frontend)
 
 on:
   push:
-    branches: [ main ]
+    branches: [main]
 
 jobs:
   build:
@@ -37,12 +37,31 @@ jobs:
           username: ${{ secrets.VM_USERNAME }}
           key: ${{ secrets.VM_SSH_KEY }}
           script: |
-            # Pull and deploy the frontend Docker image
-            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-docker-frontend:${{ github.sha }}
+            # Install Docker (if not installed)
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found. Installing..."
+              curl -fsSL https://get.docker.com -o get-docker.sh
+              sh get-docker.sh
+              sudo usermod -aG docker $USER
+              newgrp docker
+            fi
 
+            # Install Node.js (if not installed)
+            if ! command -v node &> /dev/null; then
+              echo "Node.js not found. Installing..."
+              curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
+              sudo apt-get install -y nodejs
+            fi
+                         
             docker stop monorepo-frontend || true
             docker rm monorepo-frontend || true
 
+            # Remove previous images of monorepo-docker-frontend
+            docker images --format "{{.Repository}}:{{.Tag}}" | grep "monorepo-docker-frontend" | xargs -r docker rmi || true
+
+            # Pull and deploy the frontend Docker image
+            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-docker-frontend:${{ github.sha }}
+            
             docker run -d --name monorepo-frontend \
               -p 3000:3000 \
               -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
